include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/dataconnect_generated/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    uri_does_not_exist: ignore
    uri_has_not_been_generated: ignore
    invalid_annotation_target: ignore
    deprecated_member_use: info
    prefer_final_fields: info

linter:
  rules:
    avoid_print: false
    prefer_final_fields: true
    unnecessary_brace_in_string_interps: true
    annotate_overrides: true
    library_private_types_in_public_api: false