// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW8CcJQGjnsXzuNdxaNlkCh4iwvQO8L1o',
    appId: '1:887385523054:web:aa68a85d7e10147cf9f77f',
    messagingSenderId: '887385523054',
    projectId: 'oblns-f0561',
    authDomain: 'oblns-f0561.firebaseapp.com',
    storageBucket: 'oblns-f0561.firebasestorage.app',
    measurementId: 'G-YYCRP3T6GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_RQ1oErPxcGPTXFcOEw8U9pLaqlzuVE',
    appId: '1:887385523054:android:ca81d1602dec552af9f77f',
    messagingSenderId: '887385523054',
    projectId: 'oblns-f0561',
    storageBucket: 'oblns-f0561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZ5mlDg7Bk8aLv6jV9g1cM-vE_kGmoUk',
    appId: '1:887385523054:ios:4d34dacfeeba2eb0f9f77f',
    messagingSenderId: '887385523054',
    projectId: 'oblns-f0561',
    storageBucket: 'oblns-f0561.firebasestorage.app',
    iosClientId: '887385523054-9gvsq38ceikd821f43hbr6gsd9m9dsse.apps.googleusercontent.com',
    iosBundleId: 'com.oblns.oblns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHZ5mlDg7Bk8aLv6jV9g1cM-vE_kGmoUk',
    appId: '1:887385523054:ios:4d34dacfeeba2eb0f9f77f',
    messagingSenderId: '887385523054',
    projectId: 'oblns-f0561',
    storageBucket: 'oblns-f0561.firebasestorage.app',
    iosClientId: '887385523054-9gvsq38ceikd821f43hbr6gsd9m9dsse.apps.googleusercontent.com',
    iosBundleId: 'com.oblns.oblns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW8CcJQGjnsXzuNdxaNlkCh4iwvQO8L1o',
    appId: '1:887385523054:web:66b77f010dedd1bdf9f77f',
    messagingSenderId: '887385523054',
    projectId: 'oblns-f0561',
    authDomain: 'oblns-f0561.firebaseapp.com',
    storageBucket: 'oblns-f0561.firebasestorage.app',
    measurementId: 'G-GTMZYQC2LR',
  );
}
